name = "rakshith-blog"
main = "worker.js"
compatibility_date = "2025-01-19"

# Route for worker deployment (will be updated after deployment)

# Workers Sites configuration
[site]
bucket = "./public"


# Development settings
[dev]
port = 8787
local_protocol = "http"

# Environment-specific settings
[env.production]
# Production optimizations
[env.production.performance]
cache_everything = true