name = "rakshith-website"
main = "worker.js"
compatibility_date = "2025-01-19"

# Workers Sites configuration
[site]
bucket = "./public"

# Development settings
[dev]
port = 8787
local_protocol = "http"